AWSTemplateFormatVersion: '2010-09-09'
Description: Jenkins Stack
Parameters:
  Project:
    Type: String

  TraineeName:
    Type: String

  PublicHostedZoneName:
    Description: The Route53 Zone in which to create records
    Type: String

  AmiID:
    Type: String
    Description: 'AMI ID'

  InstanceType:
    Description: The Instance type which used to build stack.
    Type: String

  ASGMaxSize:
    Description: AutoScaling max size
    Type: Number
    Default: 1

  ASGMinSize:
    Description: AutoScaling min size
    Type: Number
    Default: 1

Resources:
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub "jenkins-alb-${TraineeName}"
      Scheme: internet-facing
      Subnets:
        - "Fn::ImportValue": !Sub "${Project}-public-subnet-a"
        - "Fn::ImportValue": !Sub "${Project}-public-subnet-b"
      SecurityGroups:
        - Ref: ALBConnectionSecurityGroup

  ALBConnectionSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allowing Jenkins client connection
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        IpProtocol: tcp
        FromPort: 80
        ToPort: 80
      - CidrIp: 0.0.0.0/0
        IpProtocol: tcp
        FromPort: 443
        ToPort: 443
      VpcId:
        "Fn::ImportValue": !Sub "${Project}-vpc-id"

  ALBHTPPListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn:
            Ref: ALBTargetGroup
      LoadBalancerArn:
        Ref: LoadBalancer
      Port: 80
      Protocol: HTTP

  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 10
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 5
      Matcher:
        HttpCode: 200
      Name: !Sub 'target-group-${TraineeName}'
      Protocol: HTTP
      Port: 8080
      HealthCheckPath: '/login'
      UnhealthyThresholdCount: 3
      VpcId:
        "Fn::ImportValue": !Sub "${Project}-vpc-id"
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 120

  JenkinsASGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - "Fn::ImportValue": !Sub "${Project}-public-subnet-a"
        - "Fn::ImportValue": !Sub "${Project}-public-subnet-b"
      LaunchConfigurationName: !Ref JenkinsASLaunchConf
      MinSize: !Ref ASGMinSize
      MaxSize: !Ref ASGMaxSize
      TargetGroupARNs:
        - !Ref ALBTargetGroup
      Tags:
        - Key: Name
          Value: !Sub "${Project}-jenkins-${TraineeName}"
          PropagateAtLaunch: true

  JenkinsASLaunchConf:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: !Ref AmiID
      InstanceType: !Ref InstanceType
      KeyName: !Ref Project
      SecurityGroups:
      - !Ref JenkinsSSHSecurityGroup
      - !Ref JenkinsConnectionSecurityGroup
      UserData:
        "Fn::Base64": !Sub |
          #!/bin/bash -ex
          yum update -y
          yum remove -y java-1.7.0-openjdk
          yum install -y java-1.8.0
          wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo
          rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key
          yum install -y jenkins
          service jenkins start
          /opt/aws/bin/cfn-signal -e 0 -r "Jenkins instance Stack Complete." '${WaitHandle}'

  JenkinsSSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allowing incoming on ssh port
      SecurityGroupIngress:
      - CidrIp:
          "Fn::ImportValue": !Sub "${Project}-vpc-cidr"
        IpProtocol: '-1'
        FromPort: 0
        ToPort: 0
      - CidrIp:
          "Fn::ImportValue": !Sub "${Project}-vpc-cidr"
        IpProtocol: tcp
        FromPort: 22
        ToPort: 22
      VpcId:
        "Fn::ImportValue": !Sub "${Project}-vpc-id"

  JenkinsConnectionSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allowing Jenkins client connection
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        IpProtocol: tcp
        FromPort: 8080
        ToPort: 8080
      VpcId:
        "Fn::ImportValue": !Sub "${Project}-vpc-id"

  WaitHandle:
    Type: AWS::CloudFormation::WaitConditionHandle

  WaitCondition:
    Type: AWS::CloudFormation::WaitCondition
    Properties:
      Handle: !Ref WaitHandle
      Timeout: 1500